In [1]:
import torch
import numpy as np

In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
x_data_array = np.array(data)
x_data_array

array([[1, 2],
       [3, 4]])

From another tensor:

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

텐서 복사하기

In [5]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 




초기화: 신경망을 구축할 때 가중치나 바이어스와 같은 매개변수를 특정 값으로 초기화해야 할 필요가 있습니다. torch.ones_like()는 특정 텐서와 동일한 모양의 텐서를 1로 초기화하는 데 사용될 수 있어, 모델의 파라미터를 일관되게 초기화하는 데 도움이 됩니다.

크기와 타입 일치: 딥러닝에서는 종종 여러 텐서 간 연산을 수행해야 합니다. 이때, 연산을 수행하는 텐서들의 크기와 데이터 타입이 일치해야 합니다. torch.ones_like(data) 함수를 사용하면 data 텐서와 정확히 동일한 크기와 데이터 타입을 가진 새로운 텐서를 생성할 수 있어, 이러한 요구사항을 쉽게 충족시킬 수 있습니다.

효율적인 메모리 관리: PyTorch는 내부적으로 메모리를 효율적으로 관리하고 재사용하기 위한 메커니즘을 가지고 있습니다. torch.ones_like(data) 함수는 필요한 메모리 할당을 최적화하며, 필요한 경우 재사용할 수 있도록 해줍니다. 이는 대규모 텐서를 다룰 때 특히 중요합니다.

계산 그래프 유지: PyTorch에서는 텐서를 사용한 연산을 통해 자동 미분을 수행할 수 있습니다. torch.ones_like(data)로 생성된 텐서는 원본 데이터 data와 동일한 디바이스(CPU, GPU)에 위치하게 됩니다. 이는 계산 그래프를 유지하는 데 중요하며, 역전파 시 올바른 미분값을 계산하는 데 필요합니다.

데이터 타입과 디바이스 일치: torch.ones_like()는 원본 텐서가 저장된 디바이스(CPU, GPU 등)와 데이터 타입(float, int 등)을 자동으로 상속받아 동일한 속성의 텐서를 생성합니다. 이는 코드를 간결하게 유지하면서도 오류를 최소화할 수 있도록 돕습니다.

In [9]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # retains the properties of x_data
print(f"Ones Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[0.9999, 0.6495],
        [0.3171, 0.6105]]) 



shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [26]:
shape = (2,3,)
# shape = (2, 3, 4)
# shape = (2, 3, 4, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0731, 0.8713, 0.0859],
        [0.4114, 0.1511, 0.2869]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [29]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [34]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [31]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


torch.cat 함수는 주로 여러 텐서를 지정된 차원을 따라 연결하는 데 사용됩니다. 이 함수는 딥러닝에서 다양한 목적으로 활용되지만, 일반적으로 torch.cat을 사용하여 딥러닝 구조의 마지막에 위치하는 flatten 레이어를 직접 구현하기보다는 다른 방법이 더 자주 사용됩니다.

딥러닝 모델에서 마지막에 flatten 레이어를 구현하는 주요 목적은 다차원 텐서를 1차원 텐서로 변환하여, 완전 연결 레이어(fully connected layer) 또는 분류 레이어에 입력하기 쉽게 만드는 것입니다. 이 작업은 보통 torch.flatten 함수나 view 메소드를 사용하여 수행됩니다.

torch.cat은 주로 차원을 유지하면서 텐서를 결합할 때 사용됩니다. 예를 들어, 두 개의 피처 맵(feature map)을 채널 차원(일반적으로 차원 1)을 따라 결합하거나, 서로 다른 레이어의 출력을 결합하여 더 복잡한 특성을 모델링할 때 유용합니다.



In [35]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor 
y1 = tensor @ tensor.T   # @ 연산자는 행렬 곱셈(또는 점곱)   .T는 텐서의 전치(transpose)를 의미
y2 = tensor.matmul(tensor.T) # 위의 코드와 동일함, 연산은 주어진 텐서의 각 행과 그 전치된 버전의 각 열 사이의 내적을 계산하여 새로운 행렬을 생성  
y3 = torch.rand_like(y1)

print(f"y1: {y1}")
print(f"y2: {y2}")
print(f"y3: {y3}")



y1: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3: tensor([[0.0100, 0.9688, 0.4292, 0.0484],
        [0.3583, 0.0967, 0.8740, 0.9828],
        [0.9867, 0.2111, 0.1726, 0.6629],
        [0.2355, 0.9441, 0.5118, 0.9609]])


In [36]:
torch.matmul(tensor, tensor.T, out=y3)

# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor # 요소별 곱셈(element-wise multiplication)을 수행, 이 연산은 각 텐서의 동일한 위치에 있는 요소끼리 곱합
z2 = tensor.mul(tensor) # 위와 동일, 신경망에서 가중치를 적용하거나, 특정 패턴의 마스킹(masking) 작업을 수행
z3 = torch.rand_like(tensor)

print(f"z1: {z1}")
print(f"z2: {z2}")
print(f"z3: {z3}")


torch.mul(tensor, tensor, out=z3)

z1: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z2: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z3: tensor([[0.1423, 0.6240, 0.5858, 0.8516],
        [0.2153, 0.4252, 0.5528, 0.4737],
        [0.4351, 0.9037, 0.9813, 0.4234],
        [0.4350, 0.0351, 0.8536, 0.3361]])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Single-element tensors If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():

In [37]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


값 추출: 계산 결과를 스칼라 값으로 받고 싶을 때, 예를 들어, 손실 함수의 결과가 단일 요소 텐서로 반환되었을 때, 이 값을 Python의 float나 int와 같은 스칼라 값으로 변환하여 다루고 싶을 때 사용됩니다.

오류 검사: 특정 연산의 결과가 예상대로 단일 값을 반환하는지 확인하고, 해당 값을 직접적으로 다루기 위해 사용됩니다.

item() 메서드는 반드시 단일 요소를 포함하는 텐서에만 사용할 수 있습니다. 만약 텐서가 둘 이상의 요소를 포함하고 있다면, item() 메서드를 호출하면 오류가 발생합니다. 따라서, 이 메서드는 주로 손실 값이나 단일 성능 지표를 추출할 때 사용됩니다

In [38]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In-place operations Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

Bridge with NumPy
Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

In [39]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [40]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [41]:
n = np.ones(5)
t = torch.from_numpy(n)

In [42]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
